[project]
name = "abafraudnlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.7.6",
    "litellm>=1.79.0",
    "openai>=2.6.1",
    "pocket-agent>=0.2.23",
    "polars>=1.33.1",
    "python-dotenv>=1.2.1",
    "rank-bm25>=0.2.2",
    "rich>=14.2.0",
    "scikit-learn>=1.7.2",
    "streamlit>=1.51.0",
    "supabase>=2.22.4",
]
